juju:
  - secret-id: d1nta77mp25c78f322bg
    name: DB_HOST
    key: host
  - secret-id: d1nta77mp25c78f322bg
    name: DB_PORT
    key: port
  - secret-id: d1nta77mp25c78f322bg
    name: DB_NAME
    key: name
  - secret-id: d1nta77mp25c78f322bg
    name: DB_USER
    key: user
  - secret-id: d1nta77mp25c78f322bg
    name: DB_PASSWORD
    key: password
  - secret-id: d1nta77mp25c78f322bg
    name: DB_EVENTS_TABLE
    key: events-table

  - secret-id: d1omemvmp25c760tb20g
    name: LP_CONSUMER_KEY
    key: consumer-key
  - secret-id: d1omemvmp25c760tb20g
    name: LP_CONSUMER_SECRET
    key: consumer-secret
  - secret-id: d1omemvmp25c760tb20g
    name: LP_ACCESS_TOKEN_KEY
    key: access-key
  - secret-id: d1omemvmp25c760tb20g
    name: LP_ACCESS_TOKEN_SECRET
    key: access-secret

# env:
  # - name: LP_TEAM_NAME
  #   value: canonical
    
# vault:
  # - path: my-secrets
  #   name: env_var1
  #   key: key1