juju:
  - secret-id: d1m0i7fmp25c762ul3a0
    name: DB_HOST
    key: host
  - secret-id: d1m0i7fmp25c762ul3a0
    name: DB_PORT
    key: port
  - secret-id: d1m0i7fmp25c762ul3a0
    name: DB_NAME
    key: name
  - secret-id: d1m0i7fmp25c762ul3a0
    name: DB_USER
    key: user
  - secret-id: d1m0i7fmp25c762ul3a0
    name: DB_PASSWORD
    key: password
  - secret-id: d1m0i7fmp25c762ul3a0
    name: DB_EVENTS_TABLE
    key: events-table
# env:
#   - name: LP_TEAM_NAME
#     value: canonical
# vault:
#   - path: my-secrets
#     name: env_var1
#     key: key1